List<String> skillsList = [
  'AI',
  'Algorithms',
  'Android',
  'Android SDK',
  'APIs',
  'Arduino',
  'AWS',
  'Blockchain',
  'Bluetooth',
  'C#',
  'C++',
  'Cloud APIs',
  'Core Image',
  'Data Analytics',
  'Data Analysis',
  'Data Science',
  'Data Visualization',
  'Dart',
  'Database Design',
  'Drone SDK',
  'Django',
  'Ethereum',
  'FFmpeg',
  'Firebase',
  'Flutter',
  'GPT-3',
  'Google Analytics',
  'Google Cloud',
  'HTML5',
  'HealthKit',
  'IoT',
  'Jenkins',
  'Java',
  'JavaScript',
  'Kotlin',
  'Laravel',
  'Machine Learning',
  'MongoDB',
  'MQTT',
  'MySQL',
  'Natural Language Processing',
  'Node.js',
  'OCR',
  'OpenCV',
  'OpenGL',
  'PHP',
  'Pandas',
  'PostgreSQL',
  'Python',
  'PyPDF2',
  'React',
  'React Native',
  'ReportLab',
  'RFID',
  'Ruby on Rails',
  'Raspberry Pi',
  'Scikit-learn',
  'Shell Scripts',
  'Selenium',
  'Sensors',
  'SQL',
  'Speech APIs',
  'Speech Recognition',
  'Stripe',
  'Stripe API',
  'Stripe APIs',
  'Spring',
  'Spring Boot',
  'SQLite',
  'Swift',
  'TensorFlow',
  'Tkinter',
  'Three.js',
  'Unity',
  'VR',
  'VR SDK',
  'Web Development',
  'Web Scraping',
  'Web3',
  'WebGL',
  'WebRTC',
  'WebSocket',
  'Zeroconf'
];

List<String> categories = [
  'AI/ML',
  'Automation Solutions',
  'Blockchain',
  'Business Solutions',
  'Cloud Computing',
  'Cloud Development',
  'Cloud Solutions',
  'Data Science',
  'Education Solutions',
  'DataBase',
  'Finance Solutions',
  'Game Development',
  'IoT',
  'Mobile Development',
  'Software Development',
  'Web Development'
];

List<String> keywords = [
  '3D',
  'AI',
  'AI/ML',
  'API',
  'AR',
  'AWS',
  'Arduino',
  'Automation Solutions',
  'Blockchain',
  'Business Solutions',
  'C++',
  'CRM',
  'Data Science',
  'Django',
  'Education Solutions',
  'Ethereum',
  'FAQ',
  'Firebase',
  'Flask',
  'Flutter',
  'GPS',
  'GUI',
  'HR',
  'IVR',
  'Java',
  'JavaScript',
  'Kotlin',
  'Laravel',
  'ML',
  'MySQL',
  'NLP',
  'Node.js',
  'OCR',
  'OpenCV',
  'PHP',
  'Python',
  'React',
  'React Native',
  'Ruby on Rails',
  'SQL',
  'Solidity',
  'Spring',
  'Swift',
  'TensorFlow',
  'Unity',
  'VR',
  'WebRTC',
  'WebSocket',
  'advice',
  'advisor',
  'aggregation',
  'analysis',
  'analytics',
  'app',
  'application',
  'assistant',
  'attendance',
  'auction',
  'augmented reality',
  'automation',
  'backup',
  'banking',
  'bidding',
  'blog',
  'budgeting',
  'calendar',
  'camera',
  'chatbot',
  'checklist',
  'classification',
  'cloud',
  'coaching',
  'coding',
  'collaboration',
  'community',
  'compression',
  'conference',
  'control',
  'conversion',
  'cooking',
  'courses',
  'cryptocurrency',
  'customer management',
  'data analysis',
  'database',
  'delivery',
  'detection',
  'devices',
  'digital library',
  'document scanner',
  'drone',
  'e-commerce',
  'e-learning',
  'editing',
  'education',
  'energy monitoring',
  'event',
  'expense',
  'face recognition',
  'feedback',
  'file sharing',
  'finance',
  'fitness',
  'food',
  'forecasting',
  'forum',
  'fraud detection',
  'freelancer',
  'gallery',
  'game',
  'generator',
  'grocery',
  'guide',
  'health',
  'image editing',
  'image recognition',
  'interactive',
  'IoT',
  'job',
  'language learning',
  'learning',
  'library',
  'machine learning',
  'management',
  'marketing',
  'medical training',
  'messaging',
  'mining',
  'mobile app',
  'monitoring',
  'music',
  'navigation',
  'news',
  'node.js',
  'notifications',
  'online platform',
  'organization',
  'parking',
  'payment',
  'peer-to-peer',
  'personal assistant',
  'photo',
  'planner',
  'planning',
  'polling',
  'prediction',
  'products',
  'project',
  'quiz',
  'recommendation',
  'reminder',
  'remote',
  'resume builder',
  'retail',
  'reviews',
  'routine',
  'scanning',
  'scheduling',
  'security',
  'sentiment analysis',
  'service',
  'shopping',
  'simulation',
  'smart',
  'speech recognition',
  'sports analytics',
  'stock prediction',
  'study',
  'survey',
  'task management',
  'testing',
  'text',
  'ticketing',
  'time tracking',
  'tool',
  'tracking',
  'translation',
  'travel',
  'virtual assistant',
  'visualization',
  'voice assistant',
  'waste management',
  'web scraping',
  'website'
];
